name: Deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.37.0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - run: npm ci

      - name: Build
        run: just build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: labourreforms-uk
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}